apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentflow.name" . }}
  labels: {{- include "agentflow.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
